name: Connect to remote desktop and create a file
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: List C drive on remote server
        uses: appleboy/winrm-action@v1.3.0
        with:
          host: ${{ secrets.SERVER_IP }}
          port: 5986
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          shell: "powershell"
          command: 'Get-ChildItem C:\'
