name: Connect to remote desktop and create a file
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Connect to Windows remote desktop
        uses: Azure/rdp-windows@v1
        with:
          server-name: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 3389
      - name: Create a file on remote desktop
        shell: powershell
        run: |
          New-Item -ItemType File -Path C:\test.txt
          Set-Content -Path C:\test.txt -Value "Hello, World!"
