name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PowerShell script
        uses: actions/setup-powershell@v1
        with:
          pwsh: "latest"

      - name: Execute PowerShell script
        shell: pwsh
        run: .\deploy.ps1
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PASSWORD: ${{ secrets.SERVER_PASSWORD }}
