name: Deploy to Unix Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.VUEPRESS_SERVER_PRI_KEY_1 }}
          source: ./*  # 将编译后的文件部署到服务器
          target: /nodeserver  # 服务器上的目标路径


      - name: SSH into server and start app with PM2
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SERVER_IP }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.VUEPRESS_SERVER_PRI_KEY_1 }}
            script: |
              cd /nodeserver
              npm install
              pm2 start app.js
              pm2 save