name: Connect to remote desktop and create a file
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install windows-winrm

      - name: Run WinRM command
        run: |
          python winrm_script.py
        env:
          WINRM_HOST: ${{ secrets.SERVER_IP }}
          WINRM_USERNAME: ${{ secrets.SERVER_USERNAME }}
          WINRM_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
