name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy application
        uses: microsoft/powershell@v1
        with:
          pwsh: "pwsh.exe"
          inlineScript: |
            # 运行 PowerShell 脚本
            .\deploy.ps1
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PASSWORD: ${{ secrets.SERVER_PASSWORD }}
