name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PowerShell
        run: |
          Invoke-WebRequest -Uri https://aka.ms/install-powershell.ps1 -OutFile install-powershell.ps1
          .\install-powershell.ps1 -AddToPath

      - name: Execute PowerShell script
        shell: pwsh
        run: .\deploy.ps1
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PASSWORD: ${{ secrets.SERVER_PASSWORD }}
