name: Deploy to server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: C:\Users\<username>\Desktop
        with:
          args: rsync --delete -az --exclude '.git/' -e 'ssh -o StrictHostKeyChecking=no' $GITHUB_WORKSPACE/ ${{ env.REMOTE_USER }}@${{ env.REMOTE_HOST }}:${{ env.TARGET }}
