
          name: Deploy to Linux Server

          on:
            push:
              branches:
                - dev
          
          jobs:
            deploy:
              runs-on: ubuntu-latest
          
              steps:
                - name: Checkout code
                  uses: actions/checkout@v2
          
                - name: Copy files to server
                  uses: appleboy/scp-action@master
                  with:
                    host: ${{ secrets.SERVER_IP }}
                    username: ${{ secrets.SERVER_USERNAME }}
                    key: ${{ secrets.VUEPRESS_SERVER_PRI_KEY }}
                    source: ./
                    target: /root
          
                - name: Connect to server and restart Node.js service
                  uses: appleboy/ssh-action@master
                  with:
                    host: ${{ secrets.SERVER_IP }}
                    username: ${{ secrets.SERVER_USERNAME }}
                    key: ${{ secrets.VUEPRESS_SERVER_PRI_KEY }}
                    script: |
                      cd /root
                      npm install
                      pm2 app.js