name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in current directory
        run: |
          dir

      - name: Execute PowerShell script
        shell: pwsh
        # run: .\deploy.ps1
        run: |
          # Connect to remote server
          $username = $env:USERNAME
          $password = $env:PASSWORD | ConvertTo-SecureString -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ($username, $password)
          $session = New-PSSession -ComputerName $env:SERVER_IP -Credential $credential
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PASSWORD: ${{ secrets.SERVER_PASSWORD }}
